# Generated by Django 6.0.6 on 2026-06-30 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('marketplace_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'confirmed'))), fields=('user', 'session'), name='uniq_active_booking_per_user_session'),
        ),
    ]
