# Generated by Django 6.0.6 on 2026-06-30 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In person'), ('hybrid', 'Hybrid')], default='online', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-scheduled_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SessionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace_sessions.session')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='SessionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tags', to='marketplace_sessions.session')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_sessions', to='marketplace_sessions.tag')),
            ],
            options={
                'ordering': ('session', 'tag'),
                'unique_together': {('session', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', through='marketplace_sessions.SessionTag', to='marketplace_sessions.tag'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='marketplace_status_933c63_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['creator', 'status'], name='marketplace_creator_e0e3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['scheduled_at'], name='marketplace_schedul_384be0_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['category'], name='marketplace_categor_4f6559_idx'),
        ),
    ]
